# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogsEcstask < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takayanagishinnosuke/logs-ecstask/releases/download/v0.1.0/logs-ecstask_Darwin_x86_64.tar.gz"
      sha256 "95418ae5f28830f173d2b62eb4982d8934d857000395c513e856f9324c3258d1"

      def install
        bin.install "logs-ecstask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takayanagishinnosuke/logs-ecstask/releases/download/v0.1.0/logs-ecstask_Darwin_arm64.tar.gz"
      sha256 "e5220cea04dc78ccc133f3b9130e2309f37cc296ddb6028e8e74f903d2c15e06"

      def install
        bin.install "logs-ecstask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/takayanagishinnosuke/logs-ecstask/releases/download/v0.1.0/logs-ecstask_Linux_x86_64.tar.gz"
        sha256 "d418209616e47d2d5e3422916fc951958f361d8318c109e100b2538bd6188a0d"

        def install
          bin.install "logs-ecstask"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/takayanagishinnosuke/logs-ecstask/releases/download/v0.1.0/logs-ecstask_Linux_arm64.tar.gz"
        sha256 "818532cee0cb448824d2430bf7c4af78434db23ef5a2c5859828b5fbc3c4fac4"

        def install
          bin.install "logs-ecstask"
        end
      end
    end
  end
end
