# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpyammy < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ty-shinnosuke/mcpyammy/releases/download/v0.1.0/mcpyammy_Darwin_x86_64.tar.gz"
      sha256 "b91d7d35e258d7984726e5dae8f7df5aaa717a3291f92b77d47f3e74e2cb11f9"

      def install
        bin.install "mcpyammy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ty-shinnosuke/mcpyammy/releases/download/v0.1.0/mcpyammy_Darwin_arm64.tar.gz"
      sha256 "25d23b5113b3ac2cad76f66c1854b587d6cfd2aaf6dd8c324a00c61934950d5a"

      def install
        bin.install "mcpyammy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ty-shinnosuke/mcpyammy/releases/download/v0.1.0/mcpyammy_Linux_x86_64.tar.gz"
      sha256 "f54e919791630ad4aa4aeeac978807c16bd7c4aa3eeae0520972d6b56430fc95"
      def install
        bin.install "mcpyammy"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ty-shinnosuke/mcpyammy/releases/download/v0.1.0/mcpyammy_Linux_arm64.tar.gz"
      sha256 "1482fff391d97aeca457a0e123eaa89b5b4ce3516feb1e858fcc99ce131a8995"
      def install
        bin.install "mcpyammy"
      end
    end
  end
end
