# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RmIamPolicies < Formula
  desc ""
  homepage ""
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/takayanagishinnosuke/rm-iam-policies/releases/download/v0.1.3/rm-iam-policies_Darwin_x86_64.tar.gz"
      sha256 "85939fab822b91192733968a4d51e8432538126c8b872c6c90e8b1b5c75bd58a"

      def install
        bin.install "rm-iam-policies"
      end
    end
    on_arm do
      url "https://github.com/takayanagishinnosuke/rm-iam-policies/releases/download/v0.1.3/rm-iam-policies_Darwin_arm64.tar.gz"
      sha256 "ec70f6238868895e7fb653f5e2b5d9ea4a3a50e41885550e516749f4df89831d"

      def install
        bin.install "rm-iam-policies"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/takayanagishinnosuke/rm-iam-policies/releases/download/v0.1.3/rm-iam-policies_Linux_x86_64.tar.gz"
        sha256 "5183c09f7650dc580669cd497ed25dcce4427e315a2c514584b0d711361ecf99"

        def install
          bin.install "rm-iam-policies"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/takayanagishinnosuke/rm-iam-policies/releases/download/v0.1.3/rm-iam-policies_Linux_arm64.tar.gz"
        sha256 "c1e5b09e604345cd803e9b13025c0a631ed9973ad230cf5e17b59537c901ff0e"

        def install
          bin.install "rm-iam-policies"
        end
      end
    end
  end
end
