# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yamcp < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ty-shinnosuke/yamcp/releases/download/v0.1.0/yamcp_Darwin_x86_64.tar.gz"
      sha256 "192d5141d2b292fa371bb28f261453c6a4702a79c082b8840f4557101477f18f"

      def install
        bin.install "yamcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ty-shinnosuke/yamcp/releases/download/v0.1.0/yamcp_Darwin_arm64.tar.gz"
      sha256 "6b913dbae4e84efce9b1ae95dfb62b9b3395a0e758f7cc460554708c9884ef05"

      def install
        bin.install "yamcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ty-shinnosuke/yamcp/releases/download/v0.1.0/yamcp_Linux_x86_64.tar.gz"
      sha256 "d6f09a2c0809556a7b00e5a7d063cd86aaa68af82082f78a602f451ec825384b"
      def install
        bin.install "yamcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ty-shinnosuke/yamcp/releases/download/v0.1.0/yamcp_Linux_arm64.tar.gz"
      sha256 "4231119987382f1019a2ab91cd9134066220990a5bcea6b9a8663d7a05504c2e"
      def install
        bin.install "yamcp"
      end
    end
  end
end
